parameters:
    abenmada.backoffice.channel.default_class: 'App\Entity\Channel\Channel'
    abenmada.backoffice.channel_class: '%env(default:abenmada.backoffice.channel.default_class:ABENMADA_BACKOFFICE_CHANNEL_CLASS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Abenmada\BackofficePlugin\:
        resource: '../../*'
        exclude: '../../{Form}'

imports:
    - { resource: "packages/form.yaml" }
    - { resource: "packages/event.yaml" }
    - { resource: "packages/resource.yaml" }
    - { resource: "packages/listener.yaml" }
